# Eigenvalues and Eigenvectors

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook


$$\vec{A} = 
\begin{pmatrix}
 11 &  -1 & 0\\
-1 &  12 & -1\\
 0 &  -1 & 11
\end{pmatrix}
$$

Find the eigenvalues and eigenvectors for the equation:

$$(\vec{A} - \lambda\vec{I})\vec{v} = 0,$$
where $\vec{v}$ are the eigenvectors and $\lambda$ is the eigenvalues

In [3]:
#define matrix
A = np.array([[11,-1,0],[-1,12,-1],[0,-1,11]])

In [4]:
#find eigenvaules and eigenvectors
w, v = np.linalg.eig(A)
print(w)
print(v)

[13. 11. 10.]
[[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  1.22910000e-15  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]
